# -*- coding: utf-8 -*-

# バックアップ設定のタイトル
title = "Backup"

# バックアップ元ディレクトリ
srcDir = "C:\\folder"
# バックアップ先ディレクトリ
dstDir = "D:\\backup"
# robocopy のオプション
option = "/MIR /XJF /XJD /COPY:DAT /DCOPY:DAT /FFT /R:1 /W:10 /MT:128 /NP /TEE"

# ログファイルの出力先ディレクトリ (このオプションは任意： コメントアウトすることで無効化（/LOG オプションを付加しない）
# logDir = "D:\\backup\\logs"
# ログファイル名のプレフィックス
# logFilePrefix = "sample-"
# ログファイル名のプレフィックスに付加する日付フォーマット (C#の日付フォーマットに準拠)
# logDatetimeFmt = "yyyyMMdd-HHmmss"

# 除外するディレクトリ・ファイル (このオプションは任意： コメントアウトすることで無効化（/XD, /XF オプションを付加しない）
xdDirs = "\"System Volume Information\" \"$RECYCLE.BIN\""
# xfFiles = ""

# テストモード (true: テストモード /L オプションを付加する, false または コメントアウト: 実際にコピーする)
testMode = true

# バックアップ間隔（分）
intervalMinutes = 60
# 初回実行を遅らせるディレイ（分）
delayMinutes = 5

# sample.toml で生成される robocopy コマンド例
#     LogFilePath = {LogDir}\\{logFilename}{logDatetimeFmt}.txt
#     robocopy {SrcDir} {DstDir} {Option} /LOG:{LogFilePath} /XD {xdDirs} /XF {xfFiles}
#
# robocopy C:\folder D:\backup /L /MIR /XJF /XJD /COPY:DAT /DCOPY:DAT /FFT /R:1 /W:10 /MT:128 /NP /TEE /LOG:D:\backup\logs\sample-20210101-123456.txt /XD "System Volume Information" "$RECYCLE.BIN"
